### ISSUE TITLE
Missing definition of enum 'PointerDeclaratorSort' in the section sec:ifc:SyntaxSort:PointerDeclarator

### ISSUE THREAD

**Issue by AndreyG** [microsoft/ifc-spec#11]
https://github.com/microsoft/ifc-spec/blob/main/ltx/parse.tex#L609

**Comment by GabrielDosReis** [comment]
Thanks.  It would be good to have a LaTeX macro to typeset references to types so that:
   - we can automatically catch undefined types the way undefined references are caught
   - references to a type has a hyperlink to its definition/description site
