### ISSUE TITLE
Divergence between placeholder-type definition in the specification and .ifc produced by MSVC

### ISSUE THREAD

**Issue by AndreyG** [microsoft/ifc-spec#13]
According to the definition of `placeholder-type-structure` ([sec:ifc:TypeSort:Placeholder](https://github.com/microsoft/ifc-spec/blob/main/ltx/types.tex#L690)) its `sizeof` should be equal 8, but `entry_size` in the partition "type.placeholder" produced by MSVC (IFC-version 0.40) is equal to 12.

**Comment by cdacamar** [comment]
There is an extra member in this structure known as the 'elaboration' (what the placeholder was deduced to).  This `elaboration` field appears after `basis` and is a `TypeIndex`.

cc @GabrielDosReis

**Comment by AndreyG** [comment]
@cdacamar, thanks. Do I understand correctly, that `elaboration` could be null for dependent (1) or undeducible (2) type?
```cpp
template<typename T>
/* #1 */ auto f() { return T::foo(); }

/* #2 */ auto g(); // #2
```

**Comment by cdacamar** [comment]
In both cases the `elaboration` field would be null.
