### ISSUE TITLE
What exactly stored in "const.f64" partition?

### ISSUE THREAD

**Issue by AndreyG** [microsoft/ifc-spec#15]
The specification [says](https://github.com/microsoft/ifc-spec/blob/main/ltx/exprs.tex#L161)
> The value at that entry is a 64-bit floating point value

but `entry_size` in the partition "const.f64" produced by MSVC (IFC-version 0.40) is equal to 12.

**Comment by GabrielDosReis** [comment]
This oddity is a remnant of the early days of MSVC's serialization of 64-bit floating point type values, and has not been updated.
