### ISSUE TITLE
Divergence between base-type definition in the specification and .ifc produced by MSVC

### ISSUE THREAD

**Issue by AndreyG** [microsoft/ifc-spec#19]
The definition of `base-type` looks like
```cpp
struct BaseType {
    TypeIndex type;
    Access access;
    bool shared;
    bool pack_expanded;
};
``` 
in the specification right now ([sec:ifc:TypeSort:Base](https://github.com/microsoft/ifc-spec/blob/main/ltx/types.tex#L638)).
But `shared` and `pack_exanded` occupy exactly one bit each one in .ifc file produced by MSVC. And so it seems, that definition of `BaseType` should be
```cpp
struct BaseType {
    TypeIndex type;
    Access access;
    bool shared : 1;
    bool pack_expanded : 1;
};
```

**Comment by GabrielDosReis** [comment]
Thanks for the report. 

As a general rule, bitfields are to be avoided in the IFC spec (and hopefully implementations too).  It looks like the implementation did evolve to avoid the bitfield, but the doc was not updated to reflect the correction in the implementation.  Fixed shortly.
