### ISSUE TITLE
Cross link to Microsoft own ifc de-facto standard parser

### ISSUE THREAD

**Issue by tapika** [microsoft/ifc-spec#49]
Personally I think that IFC is great - it tries to abstract and simplify C++ language structure.

However - I as developer would prefer to have a C++ library for parsing and maybe also generating .ifc file format.

Ideally ifc could serve as base for C++ reflection, in similar manner to C#.

There exists library, which is not provided by Microsoft:

https://github.com/AndreyG/ifc-reader

and it can be used for parsing ifc file format.

- I would prefer that Microsoft would provide such library

- As open source code

- Proper unit testing would be good to have

- API is tweaked from developer perspective - for example it should be possible to enumerate classes, functions, function parameters and so on.

See also C# reflection:

https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/reflection

After we have de-facto standard ifc parsing library - we could just insert link to this git repository.

IFC documentation is useful indeed, but only for IFC parser. I would prefer to use IFC parser than analyzing IFC documentation.
Main idea is to have easy to use API, and not to long to read documentation.

**Comment by tapika** [comment]
Any progress on this @GabrielDosReis ?

**Comment by GabrielDosReis** [comment]
> Any progress on this @GabrielDosReis ?

This is a great suggestion/feature request worth repeating also on the [Visual C++ Developer Community Portal](https://developercommunity.visualstudio.com/report?space=62&entry=suggestion), to ensure it is on the MSVC team radar as they are looking for external signals in interests in such libraries and what people would like to do with them (e.g. capabilities in terms of APIs).

**Comment by tapika** [comment]
Raised as a ticket in here:

https://developercommunity.visualstudio.com/t/Microsoft-open-source-library-for-ifc-/10124743

But I'm afraid that it might get closed as irrelevant to developer community - but let's see.

I think you as main drive source should try to help to help / assist for this library to raise.

**Comment by GabrielDosReis** [comment]
Thanks for doing that!

**Comment by GabrielDosReis** [comment]
> But I'm afraid that it might get closed as irrelevant to developer community - but let's see.

I believe this is now addressed by the [Microsoft IFC SDK](https://github.com/microsoft/ifc).

Closing as fixed by that repo.
