### ISSUE TITLE
Contradiction in the definition of Operator

### ISSUE THREAD

**Issue by AndreyG** [microsoft/ifc-spec#62]
In the general description of `Operator` ([sec:ifc-operators](https://github.com/microsoft/ifc-spec/blob/609d3f8a68dddc5b1fd8b99f4fc8eef1c401de30/ltx/exprs.tex#L1729)) field `index` is defined as 12-bit value, but further concrete operators ([Monadic](https://github.com/microsoft/ifc-spec/blob/609d3f8a68dddc5b1fd8b99f4fc8eef1c401de30/ltx/exprs.tex#L1800)), ([Dyadic](https://github.com/microsoft/ifc-spec/blob/609d3f8a68dddc5b1fd8b99f4fc8eef1c401de30/ltx/exprs.tex#L2097), ...) are defined as 13-bit values.

**Comment by GabrielDosReis** [comment]
That is a time-related transcription error.  The indices all are 12-bit precision values.

**Comment by GabrielDosReis** [comment]
Fixed by #63
