### ISSUE TITLE
Misleading definition of QualifiedName expression

### ISSUE THREAD

**Issue by AndreyG** [microsoft/ifc-spec#70]
Definition of `QualifiedName` says ([sec:ifc:ExprSort:QualifiedName](https://github.com/microsoft/ifc-spec/blob/main/ltx/exprs.tex#L406))
> The _elements_ field designates the sequence of unqualified names (`ExprSort::UnqualifiedId`)...

but actually part of qualified name could be not only `UnqualifiedId`, but also `TemplateId`.

**Comment by GabrielDosReis** [comment]
You're right `ExprSort::QualifiedNamed` should really be renamed to reflect the C++ standards' [_qualified-id_](https://eel.is/c++draft/expr.prim.id.qual)
