### ISSUE TITLE
Partition of specialization form (named "form.spec") is not specified

### ISSUE THREAD

**Issue by AndreyG** [microsoft/ifc-spec#89]
This partition is mentioned twice in [DeclSort::PartialSpecialization](https://github.com/microsoft/ifc-spec/blob/03aa5c1bd5fd7946fd55ed76ee31734f6a9e603b/ltx/decls.tex#L692) and [DeclSort::Specialization](https://github.com/microsoft/ifc-spec/blob/03aa5c1bd5fd7946fd55ed76ee31734f6a9e603b/ltx/decls.tex#L720) sections, but is not defined anywhere in the specification.

**Comment by AndreyG** [comment]
@gdr-at-ms, @cdacamar could you, please, take a look at the issue, because it's really impossible to handle any compilated modules (like `std` or header unit for `<iostream>`) without processing class specializations.

**Comment by AndreyG** [comment]
cc @GabrielDosReis

**Comment by GabrielDosReis** [comment]
Fixed by #98
