### ISSUE TITLE
DeclSort::UsingDirective

### ISSUE THREAD

**Issue by DarkArc** [microsoft/ifc-spec#95]
IFC 0.43 (and earlier) contain `DeclSort::UsingDirective` but do not document its fields.

**Comment by GabrielDosReis** [comment]
`DeclSort::UsingDirective` was documented by PR #76  but not ported to the 0.43 branch.

**Comment by GabrielDosReis** [comment]
Fixed by #76 .  
_using-directive_ is represented by `DirSort::Using`.
